spring:
  application:
    name: HomeCentre-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/cozy_homes
    username: cozyhomes
    password: 852123hh
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 604800000

logging:
  config: classpath:logback-spring-dev.xml